pluginManagement {
    repositories {
        google {
            content {
                includeGroupByRegex("com\\.android.*")
                includeGroupByRegex("com\\.google.*")
                includeGroupByRegex("androidx.*")
            }
        }
        mavenCentral()
        gradlePluginPortal()
        maven { url 'https://jitpack.io' }
    }
}

// 下方除通用以外(包括)是为Android Support添加的内容
dependencyResolutionManagement {
    repositoriesMode.set(RepositoriesMode.PREFER_PROJECT) // 改为 PREFER_PROJECT 或 PREFER_SETTINGS
    repositories {
        google()
        mavenCentral()
        maven { url 'https://jitpack.io' }
    }
}

rootProject.name = "Rusted Warfare Core" // 通用
// include ':app'  // 暂时禁用 Android 模块，PC 端构建无需 Android SDK